### ISSUE TITLE
Scrolls to top when select is far down page

### ISSUE THREAD

**Issue by euperia** [iliyaZelenko/vue-cool-select#10]
Firstly - great work on this.

I have a small problem on mobile devices and mobile responsive view in the browser. 

My cool-select is quite far down on a large form.  When I focus on the select component, or start typing, it causes the browser to scroll to the top of the page.

```
<div class="col-6">
<cool-select
                      v-model="form.chosen_dog"
                      :items="animals"
                      itemText="name"
                      itemValue="id"
                    >
                      <template slot="selection" slot-scope="{ item: animal }">
                        <div class="d-flex flex-row">
                          <img :src="animal.image" :alt="animal.name" width="30" height="30" 
                          class="mr-3" />
                          <span>{{ animal.name }}</span>
                        </div>
                      </template>

                      <template slot="item" slot-scope="{ item: animal }">
                        <div class="d-flex flex-row justify-content-between">
                          <span>{{ animal.name }}</span>
                          <img :src="animal.image" :alt="animal.name" width="30" height="30" class="align-self-end" />
                        </div>
                      </template>
                    </cool-select>
</div>
```

**UPDATE**:

It seems to happen when using the 'bootstrap' theme and the component is inside bootstrap's `col-xx` elements.

See this Codesandbox for modified version of the demo that shows the issue.  Make sure you view it on a phone or in responsive mode on desktop browser: https://codesandbox.io/s/81zro028z2

**Comment by iliyaZelenko** [comment]
Thanks for using the package and for reporting an important error! 
And thanks for giving the error information so well, it really helped.

Looks like I fixed this error, you can upgrade to version `1.6.2`. [Working demo.](https://codesandbox.io/s/r42957x6x4)

I also added a new prop: `allow-mobile-scroll` with which you can turn off scrolling.

This happened because of the strange behavior of the `el.offsetTop` with `positio: relative;`.
[Simplified demo](https://codesandbox.io/s/rn53w324o).
