### ISSUE TITLE
Style is not applied

### ISSUE THREAD

**Issue by fcogutierrez** [iliyaZelenko/vue-cool-select#175]
I am using this control on following the examles but there's no style :(

![image](https://user-images.githubusercontent.com/8028313/62353873-ea332980-b50b-11e9-9c2b-e048c9f50ba7.png)

Can you help me? thanks!

**Comment by iliyaZelenko** [comment]
Hi. You are first who have this problem, this is strange.
I need more info to understand what the problem is. It would be cool if you made a reproduction.

If you click on items, are they selected? (should work if JS are ok)
Maybe you have errors in the console?

Check that you have done everything as in the documentation.
Maybe your webpack is not configured correctly (style loader)

In any case, thanks for paying attention to my component!
