### ISSUE TITLE
getItemValue's wrong logic if argument is zero

### ISSUE THREAD

**Issue by acentfrio** [iliyaZelenko/vue-cool-select#199]
Hello I probably encountered an issue with your getItemValue  function:
```js
    getItemValue (item) {
      if (!item) return null
      if (this.itemValue) return item[this.itemValue]
      if (isObject(item)) {
        const keys = Object.keys(item)
        if (keys.length === 1) {
          return item[keys[0]]
        }
        return item
      }
      return item
    },
```
the first line is prone to errors in case the "0" (zero) is passed. suggest to change this to lodash isNil check

**Comment by iliyaZelenko** [comment]
Yes, it seems there is such a problem, but it can be circumvented if you use zero as a string.

I would not want to depend on any dependency, so I can write my own version. More than lodash's `isNil`, [in fact](https://github.com/lodash/lodash/blob/4.17.15/lodash.js#L11973), It’s the same as `item == null`. Since the specification clearly states that `null` is equal to itself and `undefined` and vice versa.

In the next version, I will fix this error. I hope it is not urgent that I fix it for you?
