### ISSUE TITLE
behavior not expected in a list

### ISSUE THREAD

**Issue by danieldocki** [iliyaZelenko/vue-cool-select#61]
I need each selected item to be added to a list, but when I remove the item from the list it keeps the deleted item.

follow the example: https://github.com/danieldocki/vue-select-by-list
![screeny video 6 mar 2019 15 52 35](https://user-images.githubusercontent.com/10542/53906095-d9e45480-4028-11e9-9f2a-40bc2916662c.gif)

**Comment by iliyaZelenko** [comment]
I opened your example, launched it at my computer and understood what is wrong in example.
I can't even imagine what's wrong with my code that causes this behavior.
I tried to change your code in different ways and it is unlikely you have a problem.
It's strange, but I will try to solve  it soon.

**Comment by iliyaZelenko** [comment]
It seems to be related to the `key` prop for `ListItem` component inside App.vue. It must be completely unique (if we count the deleted items). But with unique key another strange behavior arises.

**Comment by danieldocki** [comment]
I tried this unique key and also did not, I also do not know how to explain this kind of behavior. 😞

**Comment by iliyaZelenko** [comment]
Well, I spent 5 hours on your project. And the problem was not in my library, but in your code.

The solution was quite simple, but I had to go through your code and still watch how the code of my library runs.

The problem was 3 things:
- bad `key`
- you did not specify `v-model` or `:value` in my select component [here](https://github.com/danieldocki/vue-select-by-list/blob/master/src/components/ListSearch.vue#L2).
- you mutated the `item` prop, which is a bad practice and this value was not specified in the select, besides, you created a new object and did not transfer the original one. https://github.com/danieldocki/vue-select-by-list/blob/master/src/components/ListItem.vue#L41

My PR:
https://github.com/danieldocki/vue-select-by-list/pull/1

**Comment by danieldocki** [comment]
OMG, I'm ashamed. I'll take a look at what you did, but thank you, in some event I'll pay for you some beers, ok?

**Comment by danieldocki** [comment]
@iliyaZelenko 

I made some minor modifications, now the method `removeItem` works by index, because the same item may be duplicated in the list. https://github.com/danieldocki/vue-select-by-list/blob/9307672fb39ff5cf8abf428aa22c1760395fbea7/src/App.vue#L49

Once again, thank you very much for your help.

**Comment by iliyaZelenko** [comment]
@danieldocki I thought that the problem was in my library and did not want it to be my fault for something not to work. I really spent a lot of time to figure out what the problem was, at first I thought that the problem was in my library and dug in the wrong direction.

Your donation will be very helpful and motivates me to make a greater contribution to this project. 

I sent you messages to your mail.
